const data = [
  {
    seller: 1,
    type: "Sedan",
    make: "Toyota",
    model: "Corolla",
    year: 2018,
    color: "Black",
    price: 22998.0,
    transmission_type: "Automatic",
    mileage: 40000,
    interior_color: "Gray",
    doors: 4,
    seats: 5,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/001_kvezz3.jpg",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Mazda",
    model: "Miata GT",
    year: 2006,
    color: "Black",
    price: 16500.0,
    transmission_type: "Automatic",
    mileage: 39015,
    interior_color: "Brown",
    doors: 2,
    seats: 2,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/002_kqobxh.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Acura",
    model: "RDX",
    year: 2010,
    color: "White",
    price: 13997.0,
    transmission_type: "Automatic",
    mileage: 109242,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/003_aaffm9.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Buick",
    model: "LeSabre",
    year: 2004,
    color: "Silver",
    price: 8975.0,
    transmission_type: "Automatic",
    mileage: 80889,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 29,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/004_sk9sdt.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Buick",
    model: "Encore",
    year: 2013,
    color: "White",
    price: 14900.0,
    transmission_type: "Automatic",
    mileage: 32059,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 33,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/005_d39lwo.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Buick",
    model: "Envision",
    year: 2020,
    color: "White",
    price: 31500.0,
    transmission_type: "Automatic",
    mileage: 40851,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 29,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/006_kb9j3r.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Chrysler",
    model: "Concorde",
    year: 1994,
    color: "White",
    price: 12500.0,
    transmission_type: "Automatic",
    mileage: 1032,
    interior_color: "Blue",
    doors: 4,
    seats: 5,
    mpg: 26,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/007_fyahsc.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Van",
    make: "Chrysler",
    model: "Voyager",
    year: 2020,
    color: "Grey",
    price: 24500.0,
    transmission_type: "Automatic",
    mileage: 72869,
    interior_color: "Black",
    doors: 4,
    seats: 7,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/008_u0pnrt.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Mercury",
    model: "Grand Marquis LS",
    year: 2000,
    color: "White",
    price: 7950.0,
    transmission_type: "Automatic",
    mileage: 87902,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/009_xumlsf.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "MINI",
    model: "Cooper",
    year: 2013,
    color: "Blue",
    price: 12900.0,
    transmission_type: "Automatic",
    mileage: 77335,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 36,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/010_lei70t.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Kia",
    model: "Sorento",
    year: 2016,
    color: "Blue",
    price: 14997.0,
    transmission_type: "Automatic",
    mileage: 128179,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 29,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/011_xdylhh.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Hatchback",
    make: "Subaru",
    model: "Impreza",
    year: 2013,
    color: "White",
    price: 15997.0,
    transmission_type: "Manual",
    mileage: 95358,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 36,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/012_suwp2i.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Hatchback",
    make: "Kia",
    model: "Soul",
    year: 2016,
    color: "Blue",
    price: 16997.0,
    transmission_type: "Automatic",
    mileage: 53719,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 31,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/013_fqgoai.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Kia",
    model: "Sportage",
    year: 2016,
    color: "White",
    price: 18997.0,
    transmission_type: "Automatic",
    mileage: 96118,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 26,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/014_jyfivj.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Subaru",
    model: "Forester",
    year: 2019,
    color: "Blue",
    price: 20950.0,
    transmission_type: "Manual",
    mileage: 112861,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 33,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/015_zmp3pd.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Nissan",
    model: "Murano",
    year: 2019,
    color: "Red",
    price: 20998.0,
    transmission_type: "Manual",
    mileage: 97023,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/016_tmpavb.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Hatchback",
    make: "Scion",
    model: "iM",
    year: 2016,
    color: "Red",
    price: 22997.0,
    transmission_type: "Manual",
    mileage: 43380,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/017_okkatq.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Subaru",
    model: "Impreza",
    year: 2017,
    color: "White",
    price: 22997.0,
    transmission_type: "Manual",
    mileage: 40527,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 36,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/018_aoiuo0.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Mercedes-Benz",
    model: "GLK 350",
    year: 2012,
    color: "White",
    price: 23997.0,
    transmission_type: "Automatic",
    mileage: 74669,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/019_bxb7iw.png",
    drive_type: "AWS",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Hyundai",
    model: "Tucson",
    year: 2017,
    color: "Blue",
    price: 24900.0,
    transmission_type: "Automatic",
    mileage: 42551,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/020_abhvko.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Volvo",
    model: "S60",
    year: 2020,
    color: "Black",
    price: 26900.0,
    transmission_type: "Automatic",
    mileage: 70028,
    interior_color: "White",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/021_ua7olh.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Volkswagen",
    model: "Golf SportWagen",
    year: 2019,
    color: "Blue",
    price: 27500.0,
    transmission_type: "Automatic",
    mileage: 6548,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 36,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/022_axtmbd.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Vokswagen",
    model: "Atlas",
    year: 2019,
    color: "White",
    price: 29115.0,
    transmission_type: "Automatic",
    mileage: 68182,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/023_rutkve.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "RAM",
    model: "1500",
    year: 2018,
    color: "White",
    price: 29988.0,
    transmission_type: "Automatic",
    mileage: 80648,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/024_dimxed.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Volkswagen",
    model: "Golf Alltrack",
    year: 2019,
    color: "Black",
    price: 30500.0,
    transmission_type: "Automatic",
    mileage: 13004,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/026_btsew8.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ram",
    model: "2500",
    year: 2017,
    color: "White",
    price: 34926.0,
    transmission_type: "Automatic",
    mileage: 57915,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/026_btsew8.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Land Rover",
    model: "Discovery Sport",
    year: 2018,
    color: "Blue",
    price: 34997.0,
    transmission_type: "Automatic",
    mileage: 19973,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/027_jskesv.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Jeep",
    model: "Cherokee",
    year: 2019,
    color: "Red",
    price: 34997.0,
    transmission_type: "Automatic",
    mileage: 9230,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 27,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/028_utzjey.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ram",
    model: "3500",
    year: 2014,
    color: "Blue",
    price: 34997.0,
    transmission_type: "Automatic",
    mileage: 64889,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/029_rcfekv.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Nissan",
    model: "Frontier",
    year: 2019,
    color: "Red",
    price: 35997.0,
    transmission_type: "Automatic",
    mileage: 34717,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/030_lzwre1.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Subaru",
    model: "WRX",
    year: 2018,
    color: "Blue",
    price: 36900.0,
    transmission_type: "Manual",
    mileage: 29449,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/031_umzxay.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ram",
    model: "3500",
    year: 2014,
    color: "White",
    price: 36997.0,
    transmission_type: "Automatic",
    mileage: 56463,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/032_xbnogv.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Infiniti",
    model: "QX80",
    year: 2021,
    color: "Silver",
    price: 47500.0,
    transmission_type: "Automatic",
    mileage: 65778,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/033_czszy8.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Mercury",
    model: "Grand Marquis",
    year: 2006,
    color: "Silver",
    price: 7950.0,
    transmission_type: "Automatic",
    mileage: 47424,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/034_pciicg.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Mazda",
    model: "Miata",
    year: 2007,
    color: "Red",
    price: 16975.0,
    transmission_type: "Automatic",
    mileage: 32855,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/035_rvhamg.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Mazda",
    model: "CX-5",
    year: 2015,
    color: "Blue",
    price: 18997.0,
    transmission_type: "Automatic",
    mileage: 82961,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/036_vp6jfp.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Mazda",
    model: "Miata",
    year: 2004,
    color: "White",
    price: 20998.0,
    transmission_type: "Automatic",
    mileage: 20330,
    interior_color: "Blue",
    doors: 2,
    seats: 2,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/037_juoacy.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Mazda",
    model: "CX-5",
    year: 2021,
    color: "Red",
    price: 26900.0,
    transmission_type: "Automatic",
    mileage: 18899,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 31,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/038_r6ydl9.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Mazda",
    model: "Mazda6",
    year: 2021,
    color: "Blue",
    price: 28997.0,
    transmission_type: "Automatic",
    mileage: 19903,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 35,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/039_swy5j6.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Mazda",
    model: "CX-5",
    year: 2019,
    color: "Red",
    price: 29997.0,
    transmission_type: "Automatic",
    mileage: 36835,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/040_aeyy7v.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Mazda",
    model: "Miata",
    year: 2019,
    color: "Orange",
    price: 33997.0,
    transmission_type: "Manual",
    mileage: 32745,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 34,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/041_y8ypt8.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Honda",
    model: "Element",
    year: 2005,
    color: "Silver",
    price: 10997.0,
    transmission_type: "Automatic",
    mileage: 144723,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 26,
    inventory: 1,
    photo_url: "",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "GMC",
    model: "Sierra",
    year: 2002,
    color: "Silver",
    price: 13900.0,
    transmission_type: "Automatic",
    mileage: 131176,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/042_bkijck.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "GMC",
    model: "Canyon",
    year: 2008,
    color: "Beige",
    price: 13997.0,
    transmission_type: "Automatic",
    mileage: 108103,
    interior_color: "Beige",
    doors: 2,
    seats: 2,
    mpg: 15,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/044_ozfmqd.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "MKX",
    year: 2011,
    color: "Green",
    price: 13997.0,
    transmission_type: "Automatic",
    mileage: 103121,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/045_snsptz.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Toyota",
    model: "Tacoma",
    year: 2007,
    color: "White",
    price: 16997.0,
    transmission_type: "Manual",
    mileage: 7503,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/046_rlhfda.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Lincoln",
    model: "MKZ",
    year: 2014,
    color: "Blue",
    price: 19997.0,
    transmission_type: "Automatic",
    mileage: 52928,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 31,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/047_tcogky.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "MKC",
    year: 2017,
    color: "Blue",
    price: 23997.0,
    transmission_type: "Automatic",
    mileage: 88911,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/048_npvtfz.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "GMC",
    model: "Sierra",
    year: 2014,
    color: "Blue",
    price: 27140.0,
    transmission_type: "Automatic",
    mileage: 64255,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/049_qlpzet.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "GMC",
    model: "Canyon",
    year: 2016,
    color: "Blue",
    price: 29997.0,
    transmission_type: "Automatic",
    mileage: 77954,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 29,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/050_gogm0g.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "GMC",
    model: "Sierra",
    year: 2010,
    color: "White",
    price: 31500.0,
    transmission_type: "Automatic",
    mileage: 61102,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185028/Cars/051_dl79av.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "GMC",
    model: "Acadia",
    year: 2019,
    color: "Black",
    price: 31950.0,
    transmission_type: "Automatic",
    mileage: 60510,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/052_ebqjlz.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Toyota",
    model: "Tundra",
    year: 2015,
    color: "Black",
    price: 34997.0,
    transmission_type: "Automatic",
    mileage: 74414,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/053_a0ehxj.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "GMC",
    model: "Acadia",
    year: 2017,
    color: "White",
    price: 34997.0,
    transmission_type: "Automatic",
    mileage: 56988,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/054_orfedg.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "MKC",
    year: 2019,
    color: "White",
    price: 35541.0,
    transmission_type: "Automatic",
    mileage: 30884,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/055_hmkg8i.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "MKX",
    year: 2017,
    color: "White",
    price: 38500.0,
    transmission_type: "Automatic",
    mileage: 14256,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/056_cq31du.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "Nautilus",
    year: 2019,
    color: "Red",
    price: 39674.0,
    transmission_type: "Automatic",
    mileage: 23412,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/057_y5octd.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "Nautilus",
    year: 2019,
    color: "Silver",
    price: 39675.0,
    transmission_type: "Automatic",
    mileage: 24682,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/058_toz2lv.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Honda",
    model: "Ridgeline",
    year: 2019,
    color: "White",
    price: 39997.0,
    transmission_type: "Automatic",
    mileage: 9095,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 25,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/059_fz1urn.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Honda",
    model: "Ridgeline",
    year: 2019,
    color: "Red",
    price: 42997.0,
    transmission_type: "Automatic",
    mileage: 3184,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/060_kbftxx.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Lincoln",
    model: "Nautilus",
    year: 2020,
    color: "Red",
    price: 43500.0,
    transmission_type: "Automatic",
    mileage: 7965,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/061_mynbn7.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Toyota",
    model: "4Runner",
    year: 2022,
    color: "Green",
    price: 45942.0,
    transmission_type: "Manual",
    mileage: 17408,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185029/Cars/062_lhqpd1.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Lincoln",
    model: "Continental",
    year: 2019,
    color: "White",
    price: 46500.0,
    transmission_type: "Automatic",
    mileage: 23549,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 26,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/063_m58fgh.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Van",
    make: "Honda",
    model: "Odyssey",
    year: 2015,
    color: "Blue",
    price: 47997.0,
    transmission_type: "Automatic",
    mileage: 63932,
    interior_color: "Grey",
    doors: 4,
    seats: 7,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/064_uf3zwz.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "GMC",
    model: "Yukon",
    year: 2022,
    color: "White",
    price: 76997.0,
    transmission_type: "Automatic",
    mileage: 2734,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/065_u7nds6.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Van",
    make: "Ford",
    model: "E-150",
    year: 1995,
    color: "Blue",
    price: 5950.0,
    transmission_type: "Automatic",
    mileage: 119804,
    interior_color: "Grey",
    doors: 3,
    seats: 7,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/066_sts0sk.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Chevrolet",
    model: "S-10 Blazer",
    year: 1992,
    color: "Green",
    price: 8900.0,
    transmission_type: "Automatic",
    mileage: 91775,
    interior_color: "Brown",
    doors: 2,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/067_dx76ks.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Chevrolet",
    model: "Impala",
    year: 2004,
    color: "Red",
    price: 12998.0,
    transmission_type: "Automatic",
    mileage: 51562,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 30,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/068_d1qdqh.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "Ranger",
    year: 2011,
    color: "Red",
    price: 13500.0,
    transmission_type: "Manual",
    mileage: 164539,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/069_z7qj4y.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "Colorado",
    year: 2010,
    color: "Beige",
    price: 13997.0,
    transmission_type: "Automatic",
    mileage: 114088,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/070_xodmbi.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-150",
    year: 2014,
    color: "Red",
    price: 14997.0,
    transmission_type: "Automatic",
    mileage: 144444,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/071_smqznt.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Ford",
    model: "Escape",
    year: 2013,
    color: "Black",
    price: 14997.0,
    transmission_type: "Automatic",
    mileage: 98693,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/072_riujlq.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-150",
    year: 1999,
    color: "Blue",
    price: 15900.0,
    transmission_type: "Automatic",
    mileage: 129734,
    interior_color: "Grey",
    doors: 4,
    seats: 4,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185030/Cars/073_cmccux.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "S-10",
    year: 1988,
    color: "White",
    price: 16900.0,
    transmission_type: "Manual",
    mileage: 75669,
    interior_color: "Red",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/074_vwll1s.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "C/K 1500",
    year: 1992,
    color: "White",
    price: 17950.0,
    transmission_type: "Automatic",
    mileage: 65630,
    interior_color: "Blue",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/075_bauep6.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Ford",
    model: "Escape",
    year: 2016,
    color: "White",
    price: 18500.0,
    transmission_type: "Automatic",
    mileage: 91095,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/076_hqqmvu.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "Silverado",
    year: 2009,
    color: "Blue",
    price: 18997.0,
    transmission_type: "Automatic",
    mileage: 163833,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/077_hyk6zs.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "Ranger",
    year: 2011,
    color: "Blue",
    price: 19500.0,
    transmission_type: "Manual",
    mileage: 81171,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/078_ofhs1d.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-150",
    year: 2001,
    color: "White",
    price: 19975.0,
    transmission_type: "Manual",
    mileage: 108295,
    interior_color: "Beige",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/079_mtxkbz.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Ford",
    model: "Mustang",
    year: 2011,
    color: "Blue",
    price: 19997.0,
    transmission_type: "Manual",
    mileage: 72776,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 26,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185031/Cars/080_bddaat.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Ford",
    model: "EcoSport",
    year: 2021,
    color: "Red",
    price: 20900.0,
    transmission_type: "Automatic",
    mileage: 24495,
    interior_color: "Beige",
    doors: 4,
    seats: 6,
    mpg: 29,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/081_j2a2sl.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Ford",
    model: "Thunderbird",
    year: 2004,
    color: "Red",
    price: 20997.0,
    transmission_type: "Automatic",
    mileage: 46501,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/082_pau2cy.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Chevrolet",
    model: "Tahoe",
    year: 2013,
    color: "White",
    price: 21500.0,
    transmission_type: "Automatic",
    mileage: 65562,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/083_jbbmsj.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "Silverado",
    year: 2000,
    color: "Blue",
    price: 22500.0,
    transmission_type: "Manual",
    mileage: 220493,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185023/Cars/084_jjphct.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Hatchback",
    make: "Ford",
    model: "C-Max",
    year: 2017,
    color: "White",
    price: 23997.0,
    transmission_type: "Automatic",
    mileage: 35009,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 38,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/085_brc2ul.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "Silverado",
    year: 2014,
    color: "Blue",
    price: 24900.0,
    transmission_type: "Automatic",
    mileage: 27637,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/086_nhcjuf.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Chevrolet",
    model: "Tahoe",
    year: 2013,
    color: "White",
    price: 24975.0,
    transmission_type: "Automatic",
    mileage: 28526,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/087_vi196f.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-350",
    year: 2010,
    color: "White",
    price: 24980.0,
    transmission_type: "Automatic",
    mileage: 85950,
    interior_color: "Beige",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/088_ekstl7.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Ford",
    model: "Flex",
    year: 2017,
    color: "Blue",
    price: 24997.0,
    transmission_type: "Automatic",
    mileage: 26950,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/089_bhdr3x.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-250",
    year: 2016,
    color: "White",
    price: 25900.0,
    transmission_type: "Automatic",
    mileage: 86253,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185024/Cars/090_ix1i2i.png",
    drive_type: "RWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Ford",
    model: "Fusion",
    year: 2020,
    color: "Blue",
    price: 25900.0,
    transmission_type: "Automatic",
    mileage: 64291,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 29,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/091_geemw9.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Ford",
    model: "Edge",
    year: 2017,
    color: "Beige",
    price: 26641.0,
    transmission_type: "Automatic",
    mileage: 46049,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 27,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/092_clmzyn.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "Silverado",
    year: 2013,
    color: "White",
    price: 26997.0,
    transmission_type: "Automatic",
    mileage: 56261,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/093_w2x01n.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Chevrolet",
    model: "Silverado",
    year: 2013,
    color: "White",
    price: 27997.0,
    transmission_type: "Automatic",
    mileage: 50821,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185026/Cars/094_gxcflp.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Sedan",
    make: "Ford",
    model: "Fusion",
    year: 2019,
    color: "Silver",
    price: 28400.0,
    transmission_type: "Automatic",
    mileage: 21819,
    interior_color: "Grey",
    doors: 4,
    seats: 5,
    mpg: 41,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/095_zeeune.png",
    drive_type: "FWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-250",
    year: 1996,
    color: "Red",
    price: 28900.0,
    transmission_type: "Manual",
    mileage: 130487,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185025/Cars/096_plfews.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-150",
    year: 2013,
    color: "White",
    price: 28997.0,
    transmission_type: "Automatic",
    mileage: 19758,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/097_rkq4s3.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "SUV",
    make: "Ford",
    model: "Edge",
    year: 2019,
    color: "Red",
    price: 28998.0,
    transmission_type: "Automatic",
    mileage: 44452,
    interior_color: "Black",
    doors: 4,
    seats: 5,
    mpg: 28,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/098_mw8ann.png",
    drive_type: "AWD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Truck",
    make: "Ford",
    model: "F-150",
    year: 2019,
    color: "Blue",
    price: 31977.0,
    transmission_type: "Automatic",
    mileage: 53481,
    interior_color: "Grey",
    doors: 2,
    seats: 2,
    mpg: 20,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/099_ejskuu.png",
    drive_type: "4WD",
    new_used: "used",
  },
  {
    seller: 1,
    type: "Coupe",
    make: "Chevrolet",
    model: "Corvette",
    year: 2000,
    color: "Red",
    price: 34900.0,
    transmission_type: "Automatic",
    mileage: 4436,
    interior_color: "Black",
    doors: 2,
    seats: 2,
    mpg: 36,
    inventory: 1,
    photo_url:
      "https://res.cloudinary.com/dyqjp130l/image/upload/v1669185027/Cars/100_cktbwe.png",
    drive_type: "RWD",
    new_used: "used",
  },
];


const dataCopy = () => {return [...data]}

module.exports = { dataCopy }